# Generated by Django 4.1 on 2023-04-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                ("day_id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hour",
            fields=[
                ("hour_id", models.AutoField(primary_key=True, serialize=False)),
                ("hour", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Month",
            fields=[
                ("month_id", models.AutoField(primary_key=True, serialize=False)),
                ("month", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_type",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                ("year_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                ("time_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="times",
                        to="dentalinfo.day",
                    ),
                ),
                (
                    "hour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="times",
                        to="dentalinfo.hour",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="times",
                        to="dentalinfo.month",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="times",
                        to="dentalinfo.year",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dentist",
            fields=[
                ("dentist_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dentalinfo.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="dentalinfo.dentist",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="dentalinfo.patient",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="dentalinfo.service",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="dentalinfo.time",
                    ),
                ),
            ],
        ),
    ]
