# Generated by Django 4.1 on 2023-04-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentalinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["patient", "service", "dentist", "time"]},
        ),
        migrations.AlterModelOptions(name="day", options={"ordering": ["day"]},),
        migrations.AlterModelOptions(
            name="dentist",
            options={"ordering": ["last_name", "first_name", "disambiguator"]},
        ),
        migrations.AlterModelOptions(name="hour", options={"ordering": ["hour"]},),
        migrations.AlterModelOptions(name="month", options={"ordering": ["month"]},),
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["last_name", "first_name", "disambiguator"]},
        ),
        migrations.AlterModelOptions(
            name="service", options={"ordering": ["service_type"]},
        ),
        migrations.AlterModelOptions(
            name="time", options={"ordering": ["month", "day", "year", "hour"]},
        ),
        migrations.AlterModelOptions(name="year", options={"ordering": ["year"]},),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("patient", "service", "dentist", "time"),
                name="unique_appointment",
            ),
        ),
        migrations.AddConstraint(
            model_name="dentist",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_dentist",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_patient",
            ),
        ),
        migrations.AddConstraint(
            model_name="time",
            constraint=models.UniqueConstraint(
                fields=("month", "day", "year", "hour"), name="unique_time"
            ),
        ),
    ]
