# Generated by Django 4.1 on 2023-05-03 21:08

from django.db import migrations

GROUPS = [
    {'name': 'g_client',},
    {'name': 'g_doctor',},
    {'name': 'g_scheduler',},
    {'name': 'g_admin',},
]

def add_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.create(
            name=group['name'],
        )


def remove_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.get(
            name=group['name']
        )
        group_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dentalinfo', '0003_load_patient_test_data'),
    ]

    operations = [
        migrations.RunPython(add_group_data, remove_group_data)
    ]
